CREATE DEFINER=`root`@`localhost` PROCEDURE `P_Generate`()
BEGIN

 SET SQL_SAFE_UPDATES = 0;
 DELETE FROM MismerDetail WHERE BatchID=(SELECT max(BatchID) as BatchID FROM systemupload);  

INSERT INTO mismerdetail

SELECT 
NULL ID ,
a.RowID,
(SELECT max(BatchID) as BatchID FROM systemupload) BatchID,
/*
date_format(
str_to_date(
CONCAT("20",
RIGHT(a.OPEN_DATE ,4),
 "/", 
SUBSTRING(RIGHT(a.OPEN_DATE ,7),1,2), 
 "/", 
SUBSTRING(RIGHT(a.OPEN_DATE ,9),1,2), 
 ), '%Y/%m/%d'), 
 '%Y/%m/%d')
*/

-- exp 8/14/2018 M/DD/YYYY
-- a.OPEN_DATE

 date_format(str_to_date(a.OPEN_DATE,'%m/%d/%Y'),'%Y/%m/%d')

AS OPEN_DATE , 

a.MID,
a.MERCHAN_DBA_NAME,
a.MSO,
a.SOURCE_CODE,
a.POS1,

CASE
	WHEN LEFT(a.MSO,1)='A' THEN 'WMD'
	WHEN LEFT(a.MSO,1)='B' THEN 'WPD'
	WHEN LEFT(a.MSO,1)='C' THEN 'WPL'
	WHEN LEFT(a.MSO,1)='D' THEN 'WBN'
	WHEN LEFT(a.MSO,1)='E' THEN 'WSM'
	WHEN LEFT(a.MSO,1)='F' THEN 'WSY'
	WHEN LEFT(a.MSO,1)='G' THEN 'WMK'
	WHEN LEFT(a.MSO,1)='H' THEN 'WDR'
	WHEN LEFT(a.MSO,1)='I' THEN 'WBJ'
	WHEN LEFT(a.MSO,1)='J' THEN 'WMO'
	WHEN LEFT(a.MSO,1)='K' THEN 'WPU'
	WHEN LEFT(a.MSO,1)='L' THEN 'WJS'
	WHEN LEFT(a.MSO,1)='M' THEN 'WJK'
	WHEN LEFT(a.MSO,1)='N' THEN 'WJB'
	WHEN LEFT(a.MSO,1)='O' THEN 'WJY'
	WHEN LEFT(a.MSO,1)='R' THEN 'WYK'
	WHEN LEFT(a.MSO,1)='S' THEN 'WMA'	
    
	WHEN SUBSTRING(a.MID,2,2)='01' THEN 'WMD'
	WHEN SUBSTRING(a.MID,2,2)='02' THEN 'WPD'
	WHEN SUBSTRING(a.MID,2,2)='03' THEN 'WPL'
	WHEN SUBSTRING(a.MID,2,2)='04' THEN 'WBN'
	WHEN SUBSTRING(a.MID,2,2)='05' THEN 'WSM'
	WHEN SUBSTRING(a.MID,2,2)='06' THEN 'WSY'
	WHEN SUBSTRING(a.MID,2,2)='07' THEN 'WMK'
	WHEN SUBSTRING(a.MID,2,2)='08' THEN 'WDR'
	WHEN SUBSTRING(a.MID,2,2)='09' THEN 'WBJ'
	WHEN SUBSTRING(a.MID,2,2)='10' THEN 'WJS'
	WHEN SUBSTRING(a.MID,2,2)='11' THEN 'WMO'
	WHEN SUBSTRING(a.MID,2,2)='12' THEN 'WJK'
	WHEN SUBSTRING(a.MID,2,2)='14' THEN 'WJB'
	WHEN SUBSTRING(a.MID,2,2)='15' THEN 'WJY'
	WHEN SUBSTRING(a.MID,2,2)='16' THEN 'WPU'
	WHEN SUBSTRING(a.MID,2,2)='17' THEN 'WYK'
	WHEN SUBSTRING(a.MID,2,2)='18' THEN 'WMA'    
    
 	WHEN LEFT(a.MSO,1)='' THEN 'BLANK'
  	ELSE 'ELSE'
END

as WILAYAH,


mc.Channel as CHANNEL,
 

 
 
 CASE
-- WHEN LEFT(a.MID,1)='2' THEN 'EDC'
	WHEN LEFT(a.MID,1)='3'  THEN 'YAP'

  	ELSE 'EDC'
END

as TYPE_MID

 

FROM templateuploadmismer a 

LEFT JOIN mso_channel mc ON a.MSO=mc.MSO
-- WHERE a.MSO like '%A%'
-- WHERE a.MSO IS NOT NULL OR a.MSO!=''


-- select * from mismerdetail 
-- where MERCHAN_DBA_NAME like '%EXH%'
-- where CHANNEL IS NOT NULL




;
END