CREATE DEFINER=`root`@`localhost` PROCEDURE `P_GenerateUnmatch`(in bulan int,tahun int)
BEGIN
/*
SET SQL_SAFE_UPDATES = 0;
 
DELETE FROM unmatch WHERE TYPE_MID='EDC' AND CHANNEL IS NULL;
-- AND EXTRACT(MONTH FROM OPEN_DATE)=bulan
-- AND EXTRACT(YEAR FROM OPEN_DATE)=tahun;
*/


INSERT INTO unmatch


SELECT 
RowID,
BatchID,
MID,
WILAYAH,
CHANNEL,
TYPE_MID,
OPEN_DATE

 FROM mismerdetail
WHERE TYPE_MID='EDC' AND CHANNEL IS NULL

AND EXTRACT(MONTH FROM OPEN_DATE)=bulan
AND EXTRACT(YEAR FROM OPEN_DATE)=tahun
;

END