
<!-- <script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Mismerunmatch/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script> -->
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Mismerunmatch<small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Mismerunmatch</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('mismerunmatch_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Mismerunmatch']); ?>  (Ctrl+a)" href="<?=  site_url('administrator/mismerunmatch/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', ['Mismerunmatch']); ?></a>
                        <?php }) ?>
                        <?php is_allowed('mismerunmatch_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> Mismerunmatch" href="<?= site_url('administrator/mismerunmatch/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('mismerunmatch_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf Mismerunmatch" href="<?= site_url('administrator/mismerunmatch/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Mismerunmatch</h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', ['Mismerunmatch']); ?>  <i class="label bg-yellow"><?= $mismerunmatch_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <!-- <form name="form_mismerunmatch" id="form_mismerunmatch" action="<?= base_url('administrator/mismerunmatch/index'); ?>"> -->
                  
<!-- //row  -->
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">

                     <div class="col-sm-2 padd-left-0 " >
					 <label class="form-control">TAHUN</label>
					</div>

                     <div class="col-sm-2 padd-left-0 " >


                        <select  class="form-control"  id="tahun" name="tahun"  >
                           <option  value="2018">2018</option>
                           <option  value="2017">2017</option>
                        </select>
                     </div>

                     <div class="col-sm-2 padd-left-0 " >
					 <label class="form-control">BULAN</label>
					</div>


                     <div class="col-sm-2 padd-left-0 " >
                        <select  class="form-control"  id="bulan" name="bulan"  >

                          <option value="2">Februari</option>
                          <option value="1">Januari</option>
                          <option value="3">Maret</option>
                          <option value="4">April</option>
                          <option value="5">Mei</option>
                          <option value="6">Juni</option>
                          <option value="7">Juli</option>
                          <option value="8">Agustus</option>
                          <option value="9">September</option>
                          <option  value="10">Oktober</option>
                          <option  value="11">November</option>
                          <option  value="12">Desember</option>

                        </select>
                     </div>

                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-default"  id="generate" title="generate">GENERATE</button>
                     </div>


                  </div>



                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >

                     </div>
                  </div>
               </div>
<br><br>
<!-- //row  -->
                  <div class="table-responsive"> 
                  <!-- TABEL -->
<div id="result"></div>
                  <!-- TABEL -->

                  </div>
               </div>
               <hr>
<!-- //row  -->
<!-- //row  -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
  //  console.log('readyyyyy');

const tahun = document.getElementById("tahun").value;
const bulan = document.getElementById("bulan").value;
// const result = document.getElementById("result");
const url='<?= site_url('administrator/mismerunmatch/getGenerate/') ?>'+tahun+'/'+bulan;


document.getElementById("generate").addEventListener("click", function(){
    // document.getElementById("result").innerHTML = "Hello World";
console.log(bulan);
console.log(tahun);
console.log(url);
// result.load(url);
$('#result').load(url);
}); 



  }); /*end doc ready*/
</script>