
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Mismerunmatch      <small><?= cclang('detail', ['Mismerunmatch']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/mismerunmatch'); ?>">Mismerunmatch</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Mismerunmatch</h3>
                     <h5 class="widget-user-desc">Detail Mismerunmatch</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_mismerunmatch" id="form_mismerunmatch" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RowID </label>

                        <div class="col-sm-8">
                           <?= _ent($mismerunmatch->RowID); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">BatchID </label>

                        <div class="col-sm-8">
                           <?= _ent($mismerunmatch->BatchID); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">OPEN DATE </label>

                        <div class="col-sm-8">
                           <?= _ent($mismerunmatch->OPEN_DATE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MID </label>

                        <div class="col-sm-8">
                           <?= _ent($mismerunmatch->MID); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MERCHAN DBA NAME </label>

                        <div class="col-sm-8">
                           <?= _ent($mismerunmatch->MERCHAN_DBA_NAME); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MSO </label>

                        <div class="col-sm-8">
                           <?= _ent($mismerunmatch->MSO); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SOURCE CODE </label>

                        <div class="col-sm-8">
                           <?= _ent($mismerunmatch->SOURCE_CODE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">POS1 </label>

                        <div class="col-sm-8">
                           <?= _ent($mismerunmatch->POS1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">WILAYAH </label>

                        <div class="col-sm-8">
                           <?= _ent($mismerunmatch->WILAYAH); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CHANNEL </label>

                        <div class="col-sm-8">
                           <?= _ent($mismerunmatch->CHANNEL); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TYPE MID </label>

                        <div class="col-sm-8">
                           <?= _ent($mismerunmatch->TYPE_MID); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">IS UPDATE </label>

                        <div class="col-sm-8">
                           <?= _ent($mismerunmatch->IS_UPDATE); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('mismerunmatch_update', function() use ($mismerunmatch){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit mismerunmatch (Ctrl+e)" href="<?= site_url('administrator/mismerunmatch/edit/'.$mismerunmatch->RowID); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Mismerunmatch']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/mismerunmatch/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Mismerunmatch']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
